version: '3'
services:
  web:
    image: ${SBA_DOCKER_IMAGE}
    container_name: "web-sba"
    #    restart: always # prevent other service unavailable yet
    ports:
      - ${SBA_APP_PORT}:${SBA_APP_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
    labels:
      - traefik.enable=true
      - traefik.http.routers.${ROUTER_SBA0}.entrypoints=https
      - traefik.http.routers.${ROUTER_SBA0}.tls=true
      - traefik.http.services.${ROUTER_SBA0}-service.loadbalancer.server.port=${SBA_APP_PORT}
      - traefik.http.routers.${ROUTER_SBA0}.service=${ROUTER_SBA0}-service
      - traefik.http.routers.${ROUTER_SBA1}.entrypoints=http
      - traefik.http.routers.${ROUTER_SBA1}.service=${ROUTER_SBA0}-service
      - traefik.docker.network=flycat_infra
    networks:
#      - traefik
      - infra

networks:
  infra:
    external:
      name: flycat_infra
