version: '3'
services:
  db:
    container_name: "db-mysql"
#    platform: linux/x86_64
#    image: mysql:8.0.31
    image: mariadb:10.9.3
    restart: always
    volumes:
      - ~/deploy/data/mariadb10:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - infra
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'

networks:
  infra:
    external:
      name: flycat_infra
