version: '3'
services:
  cache:
    container_name: "db-redis"
    image: redis:6.2.7-alpine
    restart: always
    volumes:
      - ~/deploy/data/redis:/data
    command: redis-server --save 180 1 --appendonly yes --loglevel warning --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    networks:
      - infra
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
networks:
  infra:
    external:
      name: flycat_infra
