version: '3'
services:
  db:
    container_name: "db_mysql"
    platform: linux/x86_64
    image: hub-mirror.c.163.com/library/mysql:5.7
    restart: always
    volumes:
      - ~/data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql
    environment:
#      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'roow'
    ports:
      - '3306:3306'

networks:
  mysql:
    external:
      name: db_mysql
