version: '3'

services:
  traefik:
    image: traefik
    container_name: "web_traefik"
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik.config.toml:/etc/traefik/traefik.config.toml # Traefik dynamic config
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${GATEWAY_DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
#      - "traefik.http.routers.dashboard.rule=(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
#      - "traefik.http.middlewares.auth.basicauth.users=zgqq:$2y$05$D3wgkNVgGqcUn9y2CzMeLuE0xW/vkho2N5LHGAa1dSwnBlNZ5uph2"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${AUTH_USERS}"
#      - "traefik.http.middlewares.auth.basicauth.users=zgqq:$2y$05$D3wgkNVgGqcUn9y2CzMeLuE0xW/vkho2N5LHGAa1dSwnBlNZ5uph2"

networks:
  webgateway:
    external:
      name: flycat_infra
